#!/usr/bin/env bash

## Load Singularity if neccesary
if ! type  singularity &> /dev/null; then
    if type module &> /dev/null; then
        module load singularity
    fi
fi

if ! type singularity &> /dev/null; then
    echo 'ERROR: singularity cannot be loaded as a module, and/or cannot be found on this system.'
    exit
else
    echo 'Singularity successfully loaded'
fi

#### Retrieve Singularity image if necessary

img='src/r-4.0.sif'
uri='library://wellerca/remote-builds/rb-63c96b25db466da3722a5a6c:latest'
desiredsum='854e2cbeb45d731d7e89f6226c9a8f97b0658313'

if [ ! -f "${img}" ]; then
    singularity pull ${img} ${uri}
fi

actualsum=$(shasum ${img} | awk '{print $1}')

if [ "${desiredsum}" != "${actualsum}" ]; then
    echo "${img} checksum failed! removing ${img}"
    rm ${img}
    echo "try again!"
    exit 1
fi

# building the singularity image was done by executing the command:
# singularity build --remote src/${img}.sif src/${img}.singularity
# (after authorizing singularity remote builder)

#### Define R parameters
pro_input='input/spe_Report_Proteins.csv' #the csv file of the protein groups quntification generated by SN
#pep_input='' #the csv file of the peptide intensity from the SN
project_name='test' #the name of this project
outdir='./output' #output dir
design_matrix='input/design_matrix.csv' #csv file of design matrix for comparison
#normalization='' # 'T' or 'F'

r_script='processing.R'

singularity run -H $PWD:/home ${img} \
    Rscript src/${r_script} \
    --pro_input ${pro_input} \
    -p ${project_name} \
    -o ${outdir} \
    --design_matrix ${design_matrix}
